replicaCount: 1

image:
  repository: ghcr.io/langfuse/langfuse
  pullPolicy: Always
  tag: "2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

langfuse:
  port: 3000
  nodeEnv: production
  nextauth:
    url: https://langfuse.monet-dev.canvass.ai
    secret: secret
  salt: salt
  telemetryEnabled: True
  nextPublicSignUpDisabled: True
  enableExperimentalFeatures: False
  extraContainers: []
  extraVolumes: []
  extraInitContainers: []
  extraVolumeMounts: []
  additionalEnv:
    - name: AUTH_GITHUB_CLIENT_ID
      value: "Ov23lidegBlKIgEc1Gmk"
    - name: AUTH_GITHUB_CLIENT_SECRET
      value: "c0c0fcce816000f6fcf051d66b2a29fca90be991"
    - name: AUTH_GITHUB_ALLOW_ACCOUNT_LINKING
      value: "false"
    - name: AUTH_DISABLE_SIGNUP
      value: "true"
    # example
    # - name: "DATABASE_PASSWORD"
    #   valueFrom:
    #     secretKeyRef:
    #       name: "my-secrets"
    #       key: "database-password"
    # - name: "EMAIL_FROM_ADDRESS"
    #   valueFrom:
    #     configMapKeyRef:
    #       name: "my-configmap"
    #       key: "email-from-address"
    # - name: DATABASE_USERNAME
    #   value: langfuse-postgres

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  ingressName: lf-nginx
  namespace: lf
  enabled: true
  className: lf-nginx
  secretName: lf-nginx-tls
  url:
    - langfuse.monet-dev.canvass.ai

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  host: dev-cacn-database01.postgres.database.azure.com
  auth:
    username: postgres
    password: 3pjFAq7P3hQ4E3cF
    database: langfuse
  deploy: false
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432

extraManifests: []
