# File generated by gen_config.py -- confirm that these settings are correct
NAMESPACE=lf

# change CLUSTER=prodccan for production cluster
CLUSTER=dev-cacn-internal-cluster01


# Standard helm chart values
NGINX_RELEASE=${NAMESPACE}-nginx
NGINX_CHART=ingress-nginx/ingress-nginx

CANVASS_RELEASE=${NAMESPACE}-deployments
CANVASS_CHART=./charts/langfuse/

CLUSTER_VALUES=../../clusters/${CLUSTER}/cluster-chart-values.yaml

# Targets to create Azure resources -- only needed when initializing the namespace
create-resource-group:
	az group create --name ${AZURE_RESOURCE_GROUP} --location ${LOCATION}

nginx:
	helm upgrade --install ${NAMESPACE}-nginx ingress-nginx/ingress-nginx  \
	--namespace=${NAMESPACE}  \
	--set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=${NAMESPACE}-canvass \
	--set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
	--set controller.ingressClassByName=true \
	--set controller.ingressClass=${NAMESPACE} \
	--set controller.ingressClassResource.name=${NAMESPACE} \
	--set controller.ingressClassResource.controllerValue="k8s.io/${NAMESPACE}" \
	--set controller.ingressClassResource.enabled=true \
	--set controller.scope.enabled=true \
	-f ./nginx-ingress-dev-values.yaml

deploy:
	helm upgrade --install \
	--namespace=${NAMESPACE} \
	${CANVASS_RELEASE} ${CANVASS_CHART}